cidre_provider: github
cidre_provider_endpoint:

cidre_git_branch_main: main
cidre_git_branch_dev: develop
cidre_git_branch_release_prefix: release
cidre_version_file: './VERSION'
cidre_changelog_file: './CHANGELOG'
cidre_data_file: './cidre_data.yaml'

cidre_data: "{{ lookup('file', cidre_data_file) | from_yaml }}"

cidre_issue_provider: github
cidre_issue_repo:
cidre_issue_provider_endpoint:
cidre_issue_provider_front: https://github.com
cidre_issue_close_state: 41
cidre_issue_open_filter: '("In Progress", Testing, Specifying, Prelive, "To Test", "To Do", "To Review", "To Release", "To Merge")'
