---

- name: Write CHANGELOG file
  when: cidre.changelog.file is defined and cidre.project.platform == "github"
  block:
  - name: Get latest milestones
    community.cidre.platform:
      platform: "{{ cidre.project.platform }}"
      resource: milestones
      context:
        repo: "{{ cidre.project.id }}"
      query_string:
        per_page: 50
        sort: due_on
        direction: desc
        state: all
    register: g_milestones
  - name: Get milestones issues
    community.cidre.platform:
      platform: "{{ cidre.project.platform }}"
      resource: issues
      context:
        repo: "{{ cidre.project.id }}"
      query_string:
        milestone: "{{ item.number }}"
        state: all
    loop: "{{ g_milestones.content }}"
    register: g_milestones_issues
  - ansible.builtin.template:
      src: "changelog.md.j2"
      dest: "{{ cidre.changelog.file }}"
  - shell: |
      git add {{ cidre.changelog.file }}
      git commit {{ cidre.changelog.file }} -m "Edit changelog"

- name: List issues
  community.cidre.platform:
    platform: "{{ cidre.project.platform }}"
    resource: issues
    context:
      repo: "{{ cidre.project.id }}"
    query_string:
      milestone: "{{ cidre_milestone.id }}"
      state: all
  register: platform_issues

- name: Git change log
  shell: |
    if [ $(git tag | wc -l) -g 0 ]
    then
      git log $(git describe --tags --abbrev=0)..HEAD --pretty='format:[%ci] @%aN (%h) %s'
    else
      git log --pretty='format:[%ci] @%aN (%h) %s'
    fi

    exit 0
  register: git_changes

- name: Build content
  set_fact:
    milestone_content: "{{ lookup('template', cidre.project.platform + '_milestone_body.md.j2') }}"

- name: Gitlab API | Update milestone
  community.cidre.platform:
    platform: "{{ cidre.project.platform }}"
    action: update
    context:
      repo: "{{ cidre.project.id }}"
      milestone: "{{ cidre_milestone.id }}"
    data:
      description: "{{ milestone_content }}"

- debug:
    msg: "Milestone updated: {{ cidre_milestone.web_url }}"
