---

- name: Get latest milestones
  ebuildy.cidre.platform:
    provider: "{{ cidre_provider }}"
    provider_endpoint: "{{ cidre_provider_endpoint }}"
    resource: milestones
    context:
    - repo: "{{ cidre_repo }}"
    query_string:
      per_page: 5
      sort: due_on
      direction: desc
      state: all
  register: g_milestones

- name: "Write CHANGELOG file for {{ cidre_issue_provider }}"
  when: cidre_issue_provider != "jira"
  block:
  - name: Get milestones associated issues
    ebuildy.cidre.platform:
      provider: "{{ cidre_issue_provider }}"
      provider_endpoint: "{{ cidre_issue_provider_endpoint }}"
      resource: issues
      context:
      - repo: "{{ cidre_repo }}"
      query_string:
        milestone: "{{ item.number | default(item.title) }}"
        state: all
    loop: "{{ g_milestones.content }}"
    loop_control:
      label: "#{{ item.id }} {{ item.title }}"
    register: g_milestones_issues
  - ansible.builtin.template:
      src: "changelog.md.j2"
      dest: "{{ cidre_changelog_file }}"


- name: Write CHANGELOG file for jira
  when: cidre_issue_provider == "jira"
  block:
  - name: Get jira associated issues
    ebuildy.cidre.platform:
      provider: "{{ cidre_issue_provider }}"
      provider_endpoint: "{{ cidre_issue_provider_endpoint }}"
      resource: search
      query_string:
        jql: "project={{cidre_issue_repo}} AND fixVersion={{ cidre_issue_component }}-{{ item.title }}"
    loop: "{{ g_milestones.content }}"
    loop_control:
      label: "#{{ item.id }} {{ item.title }}"
    register: g_milestones_issues
  - ansible.builtin.template:
      src: "changelog-jira.md.j2"
      dest: "{{ cidre_changelog_file }}"

- ignore_errors: yes
  shell: |
    git add {{ cidre_changelog_file }}
    git commit {{ cidre_changelog_file }} -m "Edit changelog"
