---

- debug:
    msg: "Current version = {{ cidre_version }}"

- debug:
    msg: "Current milestone = {{ cidre_milestone.id }} - {{ cidre_milestone.web_url }}"

- block:
  - community.cidre.platform:
      platform: "{{ cidre_platform }}"
      context:
        repo: "{{ cidre_repo }}"
    register: g_project
  - debug:
      var: g_project
