---

- when: title is not defined
  fail:
    msg: "variable title is missing!"

- name: create issue
  when: cidre_platform == "github"
  block:
  - name: Github API > Create issue
    ebuildy.cidre.platform:
      platform: "{{ cidre_platform }}"
      context:
        repo: "{{ cidre_repo }}"
      action: create
      resource: issues
      data:
        title: "{{ title }}"
        body: "{{ body | default('') }}"
        milestone: "{{ cidre_milestone.id }}"
    register: g_issue
  - debug:
      msg: "Issue created! {{ g_issue.content.html_url }}"

- name: create issue
  when: cidre_platform == "gitlab"
  block:
  - name: Gitlab API > Create issue
    ebuildy.cidre.platform:
      platform: "{{ cidre_platform }}"
      context:
        repo: "{{ cidre_repo }}"
      action: create
      resource: issues
      data:
        title: "{{ title }}"
        description: "{{ body }}"
        milestone_id: "{{ cidre_milestone.id }}"
    register: g_issue
  - debug:
      msg: "Issue created! {{ g_issue.content.web_url }}"
