---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- when: title is not defined
  fail:
    msg: "variable title is missing!"

- name: create issue
  when: cidre_issue_provider == "github"
  block:
  - name: Github API > Create issue
    ebuildy.cidre.api:
      <<: *issue_provider
      context:
      - repos: "{{ cidre_issue_repo }}"
      action: create
      resource: issues
      data:
        title: "{{ title }}"
        body: "{{ body | default('') }}"
        milestone: "{{ cidre_milestone.id }}"
    register: g_issue
  - debug:
      msg: "Issue created! {{ g_issue.content.html_url }}"

- name: create issue
  when: cidre_issue_provider == "gitlab"
  block:
  - name: Gitlab API > Create issue
    ebuildy.cidre.api:
      <<: *issue_provider
      context:
      - repos: "{{ cidre_issue_repo }}"
      action: create
      resource: issues
      data:
        title: "{{ title }}"
        description: "{{ body | default('') }}"
        milestone_id: "{{ cidre_milestone.id }}"
    register: g_issue
  - debug:
      msg: "Issue created! {{ g_issue.content.web_url }}"

##
# https://docs.atlassian.com/software/jira/docs/api/REST/8.14.0/#api/2/issue-createIssue
##
- name: create issue
  when: cidre_issue_provider == "jira"
  block:
  - name: Jira API > Create issue
    ebuildy.cidre.api:
      <<: *issue_provider
      action: create
      resource: issue
      data:
        fields:
          project:
            key: "{{ cidre_issue_repo }}"
          summary: "{{ title }}"
          description: "{{ body | default('') }}"
          components:
          - name: "{{ cidre_issue_component }}"
          fixVersions:
          - name: "{{ cidre_issue_component }}-{{ cidre_version }}"
          issuetype:
            name: Task
    register: g_issue
  - debug:
      msg: "Issue {{ g_issue.content.key }} created >> {{ cidre_issue_provider_front }}/browse/{{ g_issue.content.key }}"
