---

- name: create issue
  when: cidre.project.platform == "github"
  block:
  - name: Github API > Create issue
    community.cidre.platform:
      platform: "{{ cidre.project.platform }}"
      context:
        repo: "{{ cidre.project.id }}"
      action: create
      resource: issues
      data:
        title: "{{ title }}"
        body: "{{ body | default('') }}"
        milestone: "{{ cidre_milestone.id }}"
    register: g_issue
  - debug:
      msg: "Issue created! {{ g_issue.content.html_url }}"

- name: create issue
  when: cidre.project.platform == "gitlab"
  block:
  - name: Gitlab API > Create issue
    community.cidre.platform:
      platform: "{{ cidre.project.platform }}"
      context:
        repo: "{{ cidre.project.id }}"
      action: create
      resource: issues
      data:
        title: "{{ title }}"
        description: "{{ body }}"
        milestone_id: "{{ cidre_milestone.id }}"
    register: g_issue
  - debug:
      msg: "Issue created! {{ g_issue.content.web_url }}"
