---

- name: Check git is clean
  tags:
  - never
  - cidre_ms_open
  - cidre_ms_close
  - cidre_changelog
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  block:
  - shell: "git status --porcelain"
    register: git_status
  - fail:
      msg: "Please clean git status: {{ git_status.stdout }}"
    when: git_status.stdout != ""

- name: Check platform API authorized
  tags:
  - never
  - cidre_ms_open
  - cidre_ms_close
  - cidre_changelog
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_info
  - cidre_status
  block:
  - include_tasks:
      file: "get_user.yaml"
    vars:
      _cidre_provider: "{{ cidre_provider}}"
      _cidre_provider_endpoint: "{{ cidre_provider_endpoint }}"
  - when: cidre_issue_provider != cidre_provider
    include_tasks:
      file: "get_user.yaml"
    vars:
      _cidre_provider: "{{ cidre_issue_provider}}"
      _cidre_provider_endpoint: "{{ cidre_issue_provider_endpoint }}"

- name: Get current milestone
  tags:
  - never
  - cidre_init
  - cidre_info
  - cidre_status
  - cidre_ms_close
  - cidre_changelog
  - cidre_issue_create
  set_fact:
    cidre_milestone: "{{ lookup('ebuildy.cidre.milestone', cidre_version, repo=cidre_repo, provider=cidre_provider, provider_endpoint=cidre_provider_endpoint) }}"

- name: Initialize
  tags: ["never", "cidre_init"]
  block:
  - include_tasks:
      file: init.yaml

- name: Status
  tags: ["never", "cidre_status", "cidre_info"]
  block:
  - include_tasks:
      file: status.yaml

- name: Start release
  tags:
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_ms_open
  - never
  block:
  - include_tasks:
      file: release_start.yaml

- name: Create issue
  tags: ["cidre_issue_create", "never"]
  block:
  - include_tasks:
      file: issue_create.yaml

- name: Write changelog
  tags: ["cidre_changelog", "never"]
  block:
  - include_tasks:
      file: changelog_write.yaml

- name: Finish release
  tags: ["cidre_ms_close", "never"]
  block:
  - include_tasks:
      file: release_end.yaml
