---

- import_tasks: bootstrap_check.yaml

- name: Initialize
  tags: ["never", "cidre_init"]
  import_tasks: init.yaml

- name: Status
  tags: ["never", "cidre_status", "cidre_info"]
  import_tasks: status.yaml

- name: Start release
  tags:
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_ms_open
  - never
  import_tasks: version_bump.yaml

- name: Create issue
  tags: ["cidre_issue_create", "never"]
  import_tasks: issue_create.yaml

- name: Create release
  tags: ["cidre_release_create", "never"]
  import_tasks: release_create.yaml

- name: Write changelog
  tags: ["cidre_changelog", "never"]
  import_tasks: changelog/changelog_write.yaml

- name: Close milestone
  tags: ["cidre_ms_close", "never"]
  import_tasks: milestone_close.yaml

- name: Close milestone issues
  tags: ["cidre_ms_issues_close", "never"]
  import_tasks: milestone_issues_close.yaml
