---

- name: Get current milestone
  tags:
  - never
  - cidre_info
  - cidre_release_start
  - cidre_release_end
  - cidre_milestone_update
  - cidre_issue_create
  set_fact:
    cidre_milestone: "{{ lookup('community.cidre.milestone', cidre.version.current, repo=cidre.project.id, platform=cidre.project.platform) }}"

- name: Info
  tags: ["never", "cidre_info"]
  block:
  - include_tasks:
      file: info.yaml

- name: Start release
  tags: ["cidre_release_start", "never"]
  when: cidre.version.to != ''
  block:
  - include_tasks:
      file: release_start.yaml

- name: Create issue
  tags: ["cidre_issue_create", "never"]
  when: issue_title is defined
  block:
  - include_tasks:
      file: issue_create.yaml


- name: Update milestone
  tags: ["cidre_milestone_update", "never"]
  block:
  - include_tasks:
      file: milestone_update.yaml

- name: Finish release
  include_role:
    name: cidre
    tasks_from: release_end
  tags: ["release_end", "never"]
