---

- name: Check git is clean
  tags:
  - never
  - cidre_release_start
  - cidre_release_end
  - cidre_changelog
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  block:
  - shell: "git status --porcelain"
    register: git_status
  - fail:
      msg: "Please clean git status: {{ git_status.stdout }}"
    when: git_status.stdout != ""

- name: Check platform API authorized
  tags:
  - never
  - cidre_release_start
  - cidre_release_end
  - cidre_changelog
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_info
  - cidre_status
  block:
  - ebuildy.cidre.platform:
      platform: "{{ cidre_platform }}"
      resource: user
    register: g_user
  - debug:
      msg: "You are connected to {{ cidre_platform }} as {{ g_user.content.name }} ({{ g_user.url }})"

- name: Get current milestone
  tags:
  - never
  - cidre_init
  - cidre_info
  - cidre_status
  - cidre_release_end
  - cidre_changelog
  - cidre_issue_create
  set_fact:
    cidre_milestone: "{{ lookup('ebuildy.cidre.milestone', cidre_version, repo=cidre_repo, platform=cidre_platform) }}"

- name: Initialize
  tags: ["never", "cidre_init"]
  block:
  - include_tasks:
      file: init.yaml

- name: Info
  tags: ["never", "cidre_info"]
  block:
  - include_tasks:
      file: info.yaml

- name: Status
  tags: ["never", "cidre_status"]
  block:
  - include_tasks:
      file: status.yaml

- name: Start release
  tags:
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_release_start
  - never
  block:
  - include_tasks:
      file: release_start.yaml

- name: Create issue
  tags: ["cidre_issue_create", "never"]
  block:
  - include_tasks:
      file: issue_create.yaml

- name: Write changelog
  tags: ["cidre_changelog", "never"]
  block:
  - include_tasks:
      file: changelog_write.yaml

- name: Finish release
  tags: ["cidre_release_end", "never"]
  block:
  - include_tasks:
      file: release_end.yaml
