---

- name: Check git is clean
  tags:
  - never
  - cidre_init
  - cidre_info
  - cidre_release_start
  - cidre_release_end
  - cidre_changelog
  - cidre_issue_create
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  block:
  - shell: "git status --porcelain"
    register: git_status
  - fail:
      msg: "Please clean git status: {{ git_status.stdout }}"
    when: git_status.stdout != ""

- name: Get current milestone
  tags:
  - never
  - cidre_init
  - cidre_info
  - cidre_release_end
  - cidre_changelog
  - cidre_issue_create
  set_fact:
    cidre_milestone: "{{ lookup('community.cidre.milestone', cidre.version.current, repo=cidre.project.id, platform=cidre.project.platform) }}"

- name: Initialize
  tags: ["never", "cidre_init"]
  block:
  - include_tasks:
      file: init.yaml

- name: Info
  tags: ["never", "cidre_info"]
  block:
  - include_tasks:
      file: info.yaml

- name: Start release
  tags:
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_release_start
  - never
  block:
  - include_tasks:
      file: release_start.yaml

- name: Create issue
  tags: ["cidre_issue_create", "never"]
  when: issue_title is defined
  block:
  - include_tasks:
      file: issue_create.yaml

- name: Write changelog
  tags: ["cidre_changelog", "never"]
  block:
  - include_tasks:
      file: changelog_write.yaml

- name: Finish release
  tags: ["cidre_release_end", "never"]
  block:
  - include_tasks:
      file: release_end.yaml
