---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- import_tasks: bootstrap_check.yaml

- name: Get current milestone
  tags:
  - always
  - cidre_fetch_data
  block:
  - set_fact:
      cidre_milestone: "{{ lookup('ebuildy.cidre.milestone', cidre_version, repo=cidre_repo, api=cidre_provider, api_url=cidre_provider_endpoint) }}"
      cidre_repo_data: "{{ lookup('ebuildy.cidre.repository', cidre_repo, api=cidre_provider, api_url=cidre_provider_endpoint) }}"
  #- debug:
  #    var: cidre_milestone
  - when: cidre_repo_data.id is not defined
    fail:
      msg: "Project {{ cidre_repo }} not found!"
  - when: cidre_milestone.id is not defined
    fail:
      msg: "Milestone {{ cidre_version }} not found! You must create it manualy."

- name: Initialize
  tags: ["never", "cidre_init"]
  import_tasks: init.yaml

- name: Status
  tags: ["never", "cidre_status", "cidre_info"]
  import_tasks: status.yaml

- name: Start release
  tags:
  - cidre_bump_patch
  - cidre_bump_minor
  - cidre_bump_major
  - cidre_ms_open
  - never
  import_tasks: version_bump.yaml

- name: Create issue
  tags: ["cidre_issue_create", "never"]
  import_tasks: issue_create.yaml

- name: Create release
  tags: ["cidre_release_create", "never"]
  import_tasks: release_create.yaml

- name: Write changelog
  tags: ["cidre_changelog", "never"]
  import_tasks: changelog/changelog_write.yaml

- name: Close milestone
  tags: ["cidre_ms_close", "never"]
  import_tasks: milestone_close.yaml

- name: Close milestone issues
  tags: ["cidre_ms_issues_close", "never"]
  import_tasks: milestone_issues_close.yaml

- name: Create blog entry for all tags
  tags: ["cidre_changelog_all_tags", "never"]
  import_tasks: changelog/changelog_blog_for_all_ms.yaml
