---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- when: cidre_issue_provider == "github"
  block:
  - ebuildy.cidre.api:
      <<: *issue_provider
      resource: issues
      context:
      - repos: "{{ cidre_repo }}"
      query_string:
        milestone: "{{ cidre_milestone.number | default(cidre_milestone.title) }}"
        state: open
    register: g_status
  - loop: "{{ g_status.content }}"
    loop_control:
      label: "{{ g_issue.number | default(g_issue.id) }}"
      loop_var: g_issue
    ebuildy.cidre.api:
      provider: "{{ cidre_issue_provider }}"
      provider_endpoint: "{{ cidre_issue_provider_endpoint }}"
      action: update
      context:
      - repos: "{{ cidre_repo }}"
      - issues: "{{ g_issue.number | default(g_issue.id) }}"
      data:
        state: closed


- when: cidre_issue_provider == "jira"
  block:
  - ebuildy.cidre.api:
      <<: *issue_provider
      resource: search
      query_string:
        jql: "project={{cidre_issue_repo}} AND fixVersion={{ cidre_issue_component }}-{{ cidre_version }} AND status in {{ cidre_issue_open_filter }}"
    register: g_status
  - loop: "{{ g_status.content.issues }}"
    loop_control:
      label: "{{ g_issue.key }}"
      loop_var: g_issue
    ebuildy.cidre.api:
      <<: *issue_provider
      action: create
      resource: transitions
      context:
      - issue: "{{ g_issue.id }}"
      data:
        update:
          comment:
          - add:
              body: "Closed by cidre.io."
        transition:
          id: "{{ cidre_issue_close_state }}"
    register: g_issue_update
  - debug:
      var: g_issue_update
