---

- when:  "'cidre_bump_patch' in ansible_run_tags or 'cidre_bump_minor' in ansible_run_tags or 'cidre_bump_major' in ansible_run_tags"
  block:
  - name: Bump version - parse current version
    set_fact:
      version_major: "{{ cidre_version | regex_replace('^v(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)$', '\\g<major>') }}"
      version_minor: "{{ cidre_version | regex_replace('^v(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)$', '\\g<minor>') }}"
      version_patch: "{{ cidre_version | regex_replace('^v(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)$', '\\g<patch>') }}"

  - name: Bump version - patch
    when: "'cidre_bump_patch' in ansible_run_tags"
    set_fact:
      version_patch: "{{ version_patch | int + 1 }}"

  - name: Bump version - minor
    when: "'cidre_bump_minor' in ansible_run_tags"
    set_fact:
      version_patch: 0
      version_minor: "{{ version_minor | int + 1 }}"

  - name: Bump version - major
    when: "'cidre_bump_major' in ansible_run_tags"
    set_fact:
      version_patch: 0
      version_minor: 0
      version_major: "{{ version_major | int + 1 }}"

  - name: Bump version - build
    set_fact:
      cidre_version_to: "v{{ version_major }}.{{ version_minor }}.{{ version_patch }}"

##
# If no target version, use current version
##
- when: cidre_version_to is undefined
  set_fact:
    cidre_version_to: "{{ cidre_version }}"

- name: Git | create release branch
  shell: "git checkout -b {{ cidre_git_branch_release_prefix }}/{{ cidre_version_to }}"
  ignore_errors: yes

##
# If new version > write VERSION
##
- name: "Write into {{ cidre_version_file }}"
  when: cidre_version_to != cidre_version
  block:
  - copy:
      content: "{{ cidre_version_to }}"
      dest: "{{ cidre_version_file }}"
  - shell: |
      git add {{ cidre_version_file }}
      git commit {{ cidre_version_file }} -m "Bump version to {{ cidre_version_to }}"

- name: Get or create milestone
  include_tasks:
    file: "milestone_create.yaml"
  vars:
    ms_version: "{{ cidre_version_to }}"
