---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- when: cidre_issue_provider == "github" or cidre_issue_provider == "gitlab"
  set_fact:
    api_query:
      <<: *issue_provider
      resource: issues
      context:
      - repos: "{{ cidre_repo }}"
      query_string:
        milestone: "{{ g_milestone.number | default(g_milestone.title) }}"
        state: open

- when: cidre_issue_provider == "jira"
  set_fact:
    api_query:
      <<: *issue_provider
      resource: search
      query_string:
        jql: "project={{cidre_issue_repo}} AND fixVersion={{ cidre_issue_component }}-{{ cidre_version }}"

- ebuildy.cidre.api: "{{ api_query }}"
  register: g_status

- ebuildy.cidre.print:
    format: markdown
    msg: "{{ lookup('template', 'milestone_status.md.j2') }}"
