---

- name: List issues
  community.cidre.platform:
    platform: "{{ cidre.project.platform }}"
    resource: issues
    context:
      repo: "{{ cidre.project.id }}"
    query_string:
      milestone: "{{ cidre_milestone.number }}"
  register: platform_issues

- name: Git change log
  shell:
    cmd: "git log $(git describe --tags --abbrev=0)..HEAD --pretty='format:[%ci] @%aN (%h) %s'"
  register: git_changes

- name: Build content
  set_fact:
    milestone_content: "{{ lookup('template', cidre.project.platform + '_milestone_description.md.j2') }}"

- name: Gitlab API | Update milestone
  community.cidre.platform:
    platform: "{{ cidre.project.platform }}"
    action: update
    context:
      repo: "{{ cidre.project.id }}"
      milestone: "{{ cidre_milestone.number }}"
    data:
      description: "{{ milestone_content }}"

- when: cidre.project.platform == "github"
  debug:
    msg: "Milestone updated: {{ cidre_milestone.html_url }}"

- when: cidre.project.platform == "gitlab"
  debug:
    msg: "Milestone updated: {{ cidre_milestone.web_url }}"
