---

- when: cidre_issue_provider == "github" or cidre_issue_provider == "gitlab"
  set_fact:
    api_query:
      provider: "{{ cidre_issue_provider }}"
      provider_endpoint: "{{ cidre_issue_provider_endpoint }}"
      resource: issues
      context:
      - repos: "{{ cidre_repo }}"
      query_string:
        milestone: "{{ g_milestone.number | default(g_milestone.title) }}"
        state: open

- when: cidre_issue_provider == "jira"
  set_fact:
    api_query:
      provider: "{{ cidre_issue_provider }}"
      provider_endpoint: "{{ cidre_issue_provider_endpoint }}"
      resource: search
      query_string:
        jql: "project={{cidre_issue_repo}} AND fixVersion={{ cidre_issue_component }}-{{ cidre_version }}"

- ebuildy.cidre.api: "{{ api_query }}"
  register: g_status

- ebuildy.cidre.print:
    format: markdown
    msg: "{{ lookup('template', 'milestone_status.md.j2') }}"
