---

- set_fact:
    git_branch: "{{ cidre_git_branch_release_prefix }}/{{ cidre_version }}"

#- name: Check | git branch
#  tags: ["always"]
#  block:
#  - shell: "git branch --show-current"
#    register: git_branch
#  - fail:
#      msg: "You are not in a release ({{ git.branches.release }}/*) branch!"
#    when: git_branch.stdout | regex_search("^" ~ git.branches.release ~ "\/(.*)$")

# Check branch exist (or not, this not required)
- shell: "git rev-parse --verify --quiet {{ git_branch }} || true"
  register: shell_git_branch

# Check tag exist
- shell: "git rev-parse --verify --quiet {{ cidre_version }} || true"
  register: shell_git_tag

- name: Merge branch into main & develop
  when: shell_git_branch.stdout != ""
  shell: |
    git switch {{ cidre_git_branch_main }}
    git merge {{ git_branch }}
    git switch {{ cidre_git_branch_dev }}
    git merge {{ git_branch }}

- name: Create git tag from main branch
  when: shell_git_tag.stdout == ""
  shell: |
    git switch {{ cidre_git_branch_main }}
    git tag -a {{ cidre_version }} -m "{{ cidre_version }}: {{ cidre_milestone.web_url }}"

- name: git push
  shell: "git push origin {{ item }} || true"
  with_items:
  - "{{ cidre_git_branch_dev }}"
  - "{{ cidre_git_branch_main }}"
  - "{{ cidre_version }}"

- name: Close milestone
  block:
  - when: cidre_provider == 'github'
    set_fact:
      milestone_data:
        state: closed
  - when: cidre_provider == 'gitlab'
    set_fact:
      milestone_data:
        state_event: close
  - ebuildy.cidre.api:
      provider: "{{ cidre_provider }}"
      provider_endpoint: "{{ cidre_provider_endpoint }}"
      action: update
      context:
      - repos: "{{ cidre_repo }}"
      - milestones: "{{ cidre_milestone.id }}"
      data: "{{ milestone_data }}"

- name: Release Jira version
  when: cidre_issue_provider == "jira"
  ebuildy.cidre.api:
    provider: "jira"
    provider_endpoint: "{{ cidre_issue_provider_endpoint }}"
    action: update
    context:
    - version: "{{ cidre_data.milestone_jira.id }}"
    data:
      released: true
      releaseDate: "{{ ansible_date_time.date }}"

#- name: Delete local and remote release branch
#  shell: |
#    git branch -D {{ git_branch }}
#    git push -d origin {{ git_branch }} || true
