---
- name: Bootstrap checks
  block:
  - shell: "git status --porcelain"
    register: git_status
  - fail:
      msg: "Please clean git status: {{ git_status.stdout }}"
    when: git_status.stdout != ""

- name: Git | create release branch
  shell: "git checkout -b {{ cidre.git.branches.release }}/{{ cidre.version.to }}"
  ignore_errors: yes

- name: "Write into {{ cidre.version.file }}"
  tags: ["always", "version_write"]
  block:
  - copy:
      content: "{{ cidre.version.to }}"
      dest: "{{ cidre.version.file }}"
  - shell: "git commit {{ cidre.version.file }} -m \"Bump version to {{ cidre.version.to }}\" "
  when: cidre.version.to != cidre.version.current

- name: Get or create milestone
  when: cidre.project.platform == 'github'
  block:
  - name: create milestone
    community.cidre.platform:
      action: create
      context:
        repo: "{{ cidre.project.id }}"
      resource: milestones
      data:
        title: "{{ cidre.version.to }}"
        description: "Generated by cidre.io"

- name: Get or create milestone
  when: cidre.project.platform == 'gitlab'
  block:
  - name: create milestone
    community.cidre.platform:
      action: create
      context:
        project: "{{ cidre.project.id }}"
      resource: milestones
      data:
        title: "{{ cidre.version.to }}"
        description: "Generated by cidre.io"
