---

- when:  "'cidre_bump_patch' in ansible_run_tags or 'cidre_bump_minor' in ansible_run_tags or 'cidre_bump_major' in ansible_run_tags"
  block:
  - name: Bump version - parse current version
    set_fact:
      version_major: "{{ cidre.version.current | regex_replace('^v(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)$', '\\g<major>') }}"
      version_minor: "{{ cidre.version.current | regex_replace('^v(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)$', '\\g<minor>') }}"
      version_patch: "{{ cidre.version.current | regex_replace('^v(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)$', '\\g<patch>') }}"

  - name: Bump version - patch
    when: "'cidre_bump_patch' in ansible_run_tags"
    set_fact:
      version_patch: "{{ version_patch | int + 1 }}"

  - name: Bump version - minor
    when: "'cidre_bump_minor' in ansible_run_tags"
    set_fact:
      version_patch: 0
      version_minor: "{{ version_minor | int + 1 }}"

  - name: Bump version - major
    when: "'cidre_bump_major' in ansible_run_tags"
    set_fact:
      version_patch: 0
      version_minor: 0
      version_major: "{{ version_major | int + 1 }}"

  - name: Bump version - build
    set_fact:
      cidre_version_to: "v{{ version_major }}.{{ version_minor }}.{{ version_patch }}"

- when: cidre_version_to is not defined or cidre_version_to == ''
  fail:
    msg: "stop: target version is not defined!"

- when: cidre_version_to == cidre.version.current
  fail:
    msg: "stop: current version is already {{ cidre.version.current }}!"

- name: Git | create release branch
  shell: "git checkout -b {{ cidre.git.branches.release }}/{{ cidre_version_to }}"
  ignore_errors: yes

- name: "Write into {{ cidre.version.file }}"
  block:
  - copy:
      content: "{{ cidre_version_to }}"
      dest: "{{ cidre.version.file }}"
  - shell: |
      git add {{ cidre.version.file }}
      git commit {{ cidre.version.file }} -m "Bump version to {{ cidre_version_to }}"
  when: cidre_version_to != cidre.version.current

- name: Get or create milestone
  when: cidre.project.platform == 'github'
  block:
  - name: create milestone
    community.cidre.platform:
      platform: "{{ cidre.project.platform }}"
      action: create
      context:
        repo: "{{ cidre.project.id }}"
      resource: milestones
      data:
        title: "{{ cidre_version_to }}"
        description: "Generated by cidre.io"
    register: g_milestone
  - debug:
      msg: "milestone created {{ g_milestone.content.html_url }}"

- name: Get or create milestone
  when: cidre.project.platform == 'gitlab'
  block:
  - name: create milestone
    community.cidre.platform:
      platform: "{{ cidre.project.platform }}"
      action: create
      context:
        project: "{{ cidre.project.id }}"
      resource: milestones
      data:
        title: "{{ cidre_version_to }}"
        description: "Generated by cidre.io"
    register: g_milestone
  - debug:
      msg: "milestone created {{ g_milestone.content.web_url }}"
