---

- debug:
    msg: "Current version = {{ cidre_version }}, milestone = {{ cidre_milestone.title }} - {{ cidre_milestone.web_url }}"

- name: List issues
  ebuildy.cidre.platform:
    platform: "{{ cidre_platform }}"
    resource: issues
    context:
      repo: "{{ cidre_repo }}"
    query_string:
      milestone: "{{ (cidre_platform == 'github') | ternary(cidre_milestone.id, cidre_milestone.title) }}"
      state: open
  register: platform_issues

- loop: "{{ platform_issues.content }}"
  loop_control:
    label: ""
  debug:
    msg: "#{{ item.number | default(item.id) }} - {{ item.title }}"
