---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- debug:
    msg: "Current version = {{ cidre_version }}, milestone = {{ cidre_milestone.title }} - {{ cidre_milestone.web_url }}"

- name: ""
  ebuildy.cidre.api:
    <<: *repo_provider
    resource: milestones
    context:
    - repos: "{{ cidre_repo }}"
    query_string:
      per_page: 10
      sort: due_on
      direction: desc
      state: "{{ (cidre_provider == 'github') | ternary('open', 'active') }}"
  register: g_milestones

- name: ""
  loop: "{{ g_milestones.content }}"
  loop_control:
    label: ""
    loop_var: g_milestone
  include_tasks: milestone_status.yaml

- name: Git change log
  block:
  - shell: |
      if [ $(git tag | wc -l) -gt 0 ]
      then
        git describe --tags --abbrev=0
      fi

      exit 0
    register: git_last_tag
  - shell: |
      if [ $(git tag | wc -l) -gt 0 ]
      then
        git log $(git describe --tags --abbrev=0)..HEAD --pretty='format:[%ci] @%aN (%h) %s'
      else
        git log --pretty='format:[%ci] @%aN (%h) %s'
      fi

      exit 0
    register: git_changes
  - ebuildy.cidre.print:
      format: markdown
      msg: "{{ lookup('template', 'git_commits.md.j2') }}"
