---
- name: CI/CD management, via cidre.io
  hosts: 127.0.0.1
  connection: local
  # remote_user: user
  # become: yes
  # become_method: sudo

  # ansible-playbook ./cidre.yaml --tags "issue_create" -e 'issue_title="CI: integrate cidre"' -e issue_description="cidre"

  vars:
    cidre:
      git:
        branches:
          main: "main"
          develop: "develop"
          release: "release"
      project:
        id: ebuildy/ansible-cidre
        platform: github
      version:
        file: './VERSION'
        current: "{{ lookup('file', './VERSION') | default('v0.1.0') }}"
        to: "{{ cidre_version_to | default('') }}"

  roles:
  - cidre_workflow
