---
- name: CI/CD management, via cidre.io
  hosts: 127.0.0.1
  connection: local
  # remote_user: user
  # become: yes
  # become_method: sudo

  # ansible-playbook ./cidre.yaml --tags "issue_create" -e 'issue_title="CI: integrate cidre"' -e issue_description="cidre"

  vars:
    cidre_repo: ebuildy/ansible-cidre
    cidre_platform: github
    cidre_version: "{{ lookup('file', './VERSION') | default('v0.1.0') }}"

  roles:
  - cidre_workflow
