namespace: ebuildy
name: cidre
version: 0.12.1
readme: README.md
authors:
- Thomas Decaux <ebuildy@gmail.com>
description: |
  Toolkit to manipulate git flow (release branch / tagging),
  and gitlab via HTTP API (milestone / issue / release).
license_file: LICENSE
tags:
- git
- gitlab
- gitflow
- ci
- cd
- continuous_integration
repository: https://github.com/ebuildy/ansible-cidre
documentation: https://github.com/ebuildy/ansible-cidre
homepage: https://github.com/ebuildy/ansible-cidre
issues: https://github.com/ebuildy/ansible-cidre/issues
build_ignore:
- ./cidre.yaml
