namespace: ebuildy
name: cidre
version: 0.3.0
readme: README.md
authors:
- Thomas Decaux <ebuildy@gmail.com>
description: |
  Toolkit to manipulate git flow (release branc / tagging),
  and gitlab via HTTP API (milestone / issue / release).
licence: Apache-2.0
licence_file: LICENCE
tags:
- git
- gitlab
- git-flow
- ci
- cd
- continuous-integration
repository: https://github.com/ebuildy/ansible-cidre
documentation: https://github.com/ebuildy/ansible-cidre
homepage: https://github.com/ebuildy/ansible-cidre
issues: https://github.com/ebuildy/ansible-cidre/issues
build_ignore:
- ./cidre.yaml
