---
- name: CI/CD management, via cidre.io
  hosts: 127.0.0.1
  connection: local
  # remote_user: user
  # become: yes
  # become_method: sudo

  # ansible-playbook ./cidre.yaml --tags "issue_create" -e 'issue_title="CI: integrate cidre"' -e issue_description="cidre"

  vars:
    git:
      branches:
        main: "master"
        develop: "develop"
        release: "release"

    cidre_paths:
      version: "./VERSION"

    project:
      id: 431
      version: "{{ lookup('file', cidre_paths.version) }}"
      version_wanted: "{{ lookup('env', 'VERSION_WANTED') }}"

  tasks:
  - name: Start release
    include_role:
      name: cidre
      tasks_from: release_start
    tags: ["release_start", "never"]

  - name: Create issue
    include_role:
      name: cidre
      tasks_from: issue_create
    tags: ["issue_create", "never"]

  - name: Update milestone
    include_role:
      name: cidre
      tasks_from: milestone_update
    tags: ["milestone_update", "never"]

  - name: Finish release
    include_role:
      name: cidre
      tasks_from: release_end
    tags: ["release_end", "never"]
