---
- name: Bootstrap checks
  tags: ["always"]
  block:
  - shell: "git status --porcelain"
    register: git_status
  - fail:
      msg: "Please clean git status: {{ git_status.stdout }}"
    when: git_status.stdout != ""

- name: Git | create release branch
  tags: ["always", "git_checkout"]
  shell: "git checkout -b {{ git.branches.release }}/{{ project.version_wanted }}"

- name: "Write into {{ cidre_paths.version }}"
  tags: ["always", "version_write"]
  block:
  - copy:
      content: "{{ project.version_wanted }}"
      dest: "{{ cidre_paths.version }}"
  - shell: "git commit {{ cidre_paths.version }} -m \"Bump version via cidre\" "
  when: project.version_wanted != project.version

- name: Get or create milestone
  tags: ["always", "gitlab_milestone"]
  block:
  - name: get milestone
    uri: &gitlab_api_uri
      url: "{{ gitlab.endpoint }}/projects/{{ project.id }}/milestones?title={{ project.version_wanted }}"
      method: GET
      body_format: json
      validate_certs: no
      http_agent: "Keployr/cidre via Ansible v1.0.0"
      status_code:
      - 200
      - 201
      headers:
          Content-Type: application/json
          Authorization: Bearer {{ gitlab.access_token }}
    register: gitlab_project_milestones
  - name: create milestone
    uri:
      <<: *gitlab_api_uri
      url: "{{ gitlab.endpoint }}/projects/{{ project.id }}/milestones"
      method: POST
      body:
        title: "{{ project.version_wanted }}"
        description: "Generated by cidre.io"
      status_code: 201
    when: gitlab_project_milestones.x_total == "0"
