---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- name: Get latest milestones
  ebuildy.cidre.api:
    <<: *repo_provider
    resource: milestones
    context:
    - repos: "{{ cidre_repo }}"
    query_string:
      per_page: 5
      sort: due_on
      direction: desc
      state: all
  register: g_milestones

- name: "Write CHANGELOG file for {{ cidre_issue_provider }}"
  when: cidre_issue_provider != "jira"
  block:
  - name: Get milestones associated issues
    ebuildy.cidre.api:
      <<: *issue_provider
      resource: issues
      context:
      - repos: "{{ cidre_repo }}"
      query_string:
        milestone: "{{ item.number | default(item.title) }}"
        state: all
    loop: "{{ g_milestones.content }}"
    loop_control:
      label: "#{{ item.id }} {{ item.title }}"
    register: g_milestones_issues
  - ansible.builtin.template:
      src: "changelog.md.j2"
      dest: "{{ cidre_changelog_file }}"


- name: Write CHANGELOG file for jira
  when: cidre_issue_provider == "jira"
  block:
  - name: Get jira associated issues
    ignore_errors: yes
    ebuildy.cidre.api:
      <<: *issue_provider
      resource: search
      query_string:
        jql: "project={{cidre_issue_repo}} AND fixVersion={{ cidre_issue_component }}-{{ item.title }}"
    loop: "{{ g_milestones.content }}"
    loop_control:
      label: "#{{ item.id }} {{ item.title }}"
    register: g_milestones_issues
  - ansible.builtin.template:
      src: "changelog-jira.md.j2"
      dest: "{{ cidre_changelog_file }}"

- ignore_errors: yes
  shell: |
    git add {{ cidre_changelog_file }} > /dev/null 2>&1
    git commit {{ cidre_changelog_file }} -m "Edit changelog" > /dev/null 2>&1
