---

- when: false
  set_fact:
    repo_provider: &repo_provider
      api: "{{ cidre_provider }}"
      api_url: "{{ cidre_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"
    issue_provider: &issue_provider
      api: "{{ cidre_issue_provider }}"
      api_url: "{{ cidre_issue_provider_endpoint }}"
      #api_token: "{{ cidre_blog_api_token }}"

- when: cidre_issue_provider == "jira"
  set_fact:
    search_query:
      <<: *issue_provider
      resource: search
      query_string:
        jql: "project={{cidre_issue_repo}} AND fixVersion={{ cidre_issue_component }}-{{ cidre_milestone.title }}"

- when: cidre_issue_provider != "jira"
  set_fact:
    search_query:
      <<: *issue_provider
      resource: issues
      context:
      - repos: "{{ cidre_repo }}"
      query_string:
        milestone: "{{ (cidre_provider == 'github') | ternary(cidre_milestone.id, cidre_milestone.title) }}"
        state: all

- name: "{{ cidre_issue_provider }} > List issues"
  ebuildy.cidre.api: "{{ search_query }}"
  register: platform_issues

- name: Git change log
  shell: |
    if [ $(git tag | wc -l) -gt 0 ]
    then
      if [ $(git tag -l "{{ cidre_version }}") ]; then
        # current version already deployed
        git log {{ cidre_version }}^..{{ cidre_version }} --pretty='format:[%ci] @%aN (%h) %s'
      else
        git log {{ cidre_version }}..HEAD --pretty='format:[%ci] @%aN (%h) %s'
      fi
    else
      git log --pretty='format:[%ci] @%aN (%h) %s'
    fi

    exit 0
  register: git_changes

- name: Build content
  set_fact:
    milestone_content: "{{ lookup('template', cidre_issue_provider + '_milestone_body.md.j2') }}"

- name: "{{ cidre_provider }} > Update milestone"
  ebuildy.cidre.api:
    <<: *repo_provider
    action: update
    context:
    - repos: "{{ cidre_repo }}"
    - milestones: "{{ cidre_milestone.id }}"
    data:
      description: "{{ milestone_content }}"

- when: cidre_blog_provider == "confluence"
  name: Confluence
  vars:
    ms_version: "{{ cidre_version }}"
  include_tasks:
    file: "confluence_write_page.yaml"

- debug:
    msg: "Milestone updated: {{ cidre_milestone.web_url }}"
