---

- when: false
  set_fact: &provider
    api: "{{ cidre_blog_provider }}"
    api_url: "{{ cidre_blog_api_endpoint }}"
    api_token: "{{ cidre_blog_api_token }}"

- name: Search existing page
  ebuildy.cidre.api:
    <<: *provider
    resource: content
    query_string:
      space: "{{ cidre_blog_repo }}"
      title: MileStone {{ ms_version }}
  register: confluence_page_response

- when: confluence_page_response.content.size > 0
  name: "Remove existing page {{ confluence_page_response.content.results[0].id }}"
  ebuildy.cidre.api:
    <<: *provider
    action: delete
    context:
    - content: "{{ confluence_page_response.content.results[0].id }}"

- block:
  - shell: git tag  --sort=taggerdate | grep {{ ms_version }} -A1 | tail -n 1
    register: git_tag_previous
  - set_fact:
      git_tag_previous: "{{ git_tag_previous.stdout }}"

- shell: |
    git log \
    {% if git_tag_previous == ms_version %}
      {{ ms_version }} \
    {% elif git_tag_previous != "" %}
      {{ git_tag_previous }}..{{ ms_version }} \
    {% endif %}
     --pretty='format:{{cidre_blog_changelog_git_format}}'
  register: git_changes

- shell: |
    git log \
    {% if git_tag_previous == ms_version %}
      {{ ms_version }} \
    {% elif git_tag_previous != "" %}
      {{ git_tag_previous }}..{{ ms_version }} \
    {% endif %}
    --pretty="format:%cd" --date=format:'%A  %Y-%m-%d %H:%M:%S' | tail -n 1
  register: git_changes_date_min

- shell: |
    git log \
    {% if git_tag_previous == ms_version %}
      {{ ms_version }} \
    {% elif git_tag_previous != "" %}
      {{ git_tag_previous }}..{{ ms_version }} \
    {% endif %}
    --reverse --pretty="format:%cd" --date=format:'%A  %Y-%m-%d %H:%M:%S' | tail -n 1
  register: git_changes_date_max

- name: Create page
  vars:
    my_cidre_milestone: "{{ lookup('ebuildy.cidre.milestone', ms_version, repo=cidre_repo, api=cidre_provider, api_url=cidre_provider_endpoint) }}"
  ebuildy.cidre.api:
    <<: *provider
    action: create
    resource: content
    data:
      type: page
      title: MileStone {{ ms_version }}
      space:
        key: "{{ cidre_blog_repo }}"
      ancestors:
      - id: "{{ cidre_blog_ancestor }}"
      body:
        storage:
          value: "{{ lookup('template', 'confluence_milestone_body.html.j2') }}"
          representation: storage
  register: confluence_page_response

- debug:
    #var: confluence_page_response
    msg: "Page at {{ confluence_page_response.content._links.webui }}"
