---

- when: false
  set_fact: &provider
    provider: "{{ cidre_blog_provider }}"
    provider_endpoint: "{{ cidre_blog_api_endpoint }}"
    provider_access_token: "{{ cidre_blog_api_token }}"

- name: Search existing page
  ebuildy.cidre.api:
    <<: *provider
    resource: content
    query_string:
      space: "{{ cidre_blog_repo }}"
      title: MileStone {{ ms_version }}
  register: confluence_page_response

- when: confluence_page_response.content.size > 0
  name: "Remove existing page {{ confluence_page_response.content.results[0].id }}"
  ebuildy.cidre.api:
    <<: *provider
    action: delete
    context:
    - content: "{{ confluence_page_response.content.results[0].id }}"

- name: Git change log
  vars:
    git_format: "[%ci] @%aN %h <a href=\"{{ cidre_repo_data.web_url }}/-/commit/%H\">%s</a>"
  shell: |
    if [ $(git tag | wc -l) -gt 0 ]
    then
      if [ $(git tag -l "{{ ms_version }}") ]; then
        # current version already deployed
        git log {{ ms_version }}^..{{ ms_version }} --pretty='format:{{git_format}}'
      else
        git log {{ ms_version }}..HEAD --pretty='format:{{git_format}}'
      fi
    else
      git log --pretty='format:{{git_format}}'
    fi

    exit 0
  register: git_changes

- name: Create page
  vars:
    cidre_milestone: "{{ lookup('ebuildy.cidre.milestone', ms_version, repo=cidre_repo, provider=cidre_provider, provider_endpoint=cidre_provider_endpoint) }}"
    tag_web_url: https://git.qwant.ninja/product/analytic/infra/hot/-/tags/v1.2.0
  ebuildy.cidre.api:
    <<: *provider
    action: create
    resource: content
    data:
      type: page
      title: MileStone {{ ms_version }}
      space:
        key: "{{ cidre_blog_repo }}"
      ancestors:
      - id: "{{ cidre_blog_ancestor }}"
      body:
        storage:
          value: "{{ lookup('template', 'confluence_milestone_body.html.j2') }}"
          representation: storage
  register: confluence_page_response

- debug:
    #var: confluence_page_response
    msg: "Page at {{ confluence_page_response.content._links.webui }}"
