---
name: CI
'on':
  push:
    branches:
      - main
  pull_request:

jobs:

  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['2.7', '3.7']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/cidre

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible base (devel branch)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Run sanity tests on Python ${{ matrix.python_version }}
        run: make test-sanity PYTHON_VERSION=${{ matrix.python_version }}
        working-directory: ./ansible_collections/community/cidre

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Our old integration tests fail under newer Python versions.
        python_version: ['3.6']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/cidre

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible base (devel branch)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Run unit tests on Python ${{ matrix.python_version }}
        run: make test-unit PYTHON_VERSION=${{ matrix.python_version }}
        working-directory: ./ansible_collections/community/cidre

      - name: Run integration tests on Python ${{ matrix.python_version }}
        run: make test-integration PYTHON_VERSION=${{ matrix.python_version }}
        working-directory: ./ansible_collections/community/cidre

      - name: Generate coverage report.
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version
        working-directory: ./ansible_collections/community/cidre

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
